### ISSUE TITLE
make preview plz

### ISSUE THREAD

**Issue by Jays-Scripts** [boiidevelopment/boii_target#1]

**Comment by CaseIRL** [comment]
![image](https://github.com/boiidevelopment/boii_target/assets/90377400/14be0a9c-9190-4c4e-b27e-8ac083db41ab)

I mean its just a regular targeting system thing qb-target but i guess slightly better *(better is subjective ofc)*? :P

Have attached an image of most recent redesign anyway, it is now at a stage where it can be used properly, just still not release ready as it needs some bridge functions adding to make the change over easier for people who want to change.
